name: flowery_rider_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  logger: ^2.6.0  # for logging purpose
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.3
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_form_builder: ^10.2.0
  injectable: ^2.7.1+4
  retrofit: ^4.9.2
  intl: any
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  bloc: ^9.1.0
  dio: ^5.9.0
  equatable: ^2.0.7
  google_fonts: ^6.3.3
  dart_mappable: ^4.2.0
  pretty_dio_logger: ^1.4.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  firebase_core: ^4.4.0
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  provider: ^6.1.5+1
  geocoding: ^4.0.0  
  easy_localization: ^3.0.8
  easy_localization_loader: ^2.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.1
  json_serializable: ^6.10.0  
    # add the generator to your dev_dependencies  
  injectable_generator: ^2.9.1
  # add build runner if not already added  
  build_runner: ^2.4.7  
  mockito: ^5.6.1
  test: ^1.26.3
  dart_mappable_builder: ^4.2.0
  bloc_test: ^10.0.0
  easy_localization_generator: ^0.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
    - assets/svg/
scripts:
  locale: dart run tools\generate_locale.dart
  routes: dart run tools\generate_routes.dart